# NAN(not a number ) & INF(infinite number)

In [32]:
# In real life application we will often encounter arrays(says columbs )
#with data elements at some part either missing(categorised as 'nan' or 'inf')
# we will see such examples in this tutorial 
import numpy as np
list1=[[1,2,3,4,5],[6,7,8,9,10]]
list1
arr1=np.array(list1,dtype="float")
arr1  # so here we have a 2-d array with all the numerical elements 


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [36]:
# suppose we have a null value at sum places  lets say the first and second column of the first row 
#has been filled with 'nan' and 'inf '.
arr1[0,0]=np.nan
arr1[0,1]=np.inf
arr1

array([[nan, inf,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [55]:
# now we have a function to find out if the array has "nan" or "inf" as well
np.isnan(arr1)

array([[ True, False, False, False, False],
       [False, False, False, False, False]])

In [57]:
np.isinf(arr1) # now we can use these two functions to find out the missing ('nan' or 'inf') in the matrix

array([[False,  True, False, False, False],
       [False, False, False, False, False]])

In [65]:
flags=np.isnan(arr1)|np.isinf(arr1)
flags
# now we can use this conditional in our existing array 



array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [ ]:
arr1[flags]