In [1]:
#THIS IS THE FIRST LECTURE EXERCISE ON NUMPY PORTION IN UDEMY COURSE.
# NUMPY LIBRARY PROVIDES ARRAY ie. different from List in Several ways as follows:-
#The list can be appended after they have been created (we can add more elements)
# But for Numpy this can't be done as array once created cannot be appended with more elements.
#Array further allow vectorized operations (elementary operations)
# List can contain elements of different data types while Array can onyl contain elements of same data type only.


In [6]:
import numpy as np
list1=[1,2,3,4,5,6]

list1 # Here i would demonstrate how list is different from array .

[1, 2, 3, 4, 5, 6]

In [8]:
arr1=np.array(list1)
arr1      # arr1 is a array that has been formed  from list elements . similarly a list can be formed from array 

array([1, 2, 3, 4, 5, 6])

In [47]:
list2=list(arr1)
list2 

[2, 3, 4, 5, 6, 7, 2, 11]

In [49]:
# the other way to make a list out of array is  'tolist()' method .
newlist=arr1.tolist()
newlist

[2, 3, 4, 5, 6, 7, 2, 11]

In [14]:
#lets find out if we can append an array like we do with a list 

list1.append(10)
list1


[1, 2, 3, 4, 5, 6, 1, 10]

In [15]:
#now lets try the same with Array as well and find out ?? As you can see . we cannot append or introduce new element
arr1.append(10)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [17]:
# We can always perform batch operations or (vectorization ) with array elements
list1=list1+1  # we see such batch elementary operations are not possible with lists

TypeError: can only concatenate list (not "int") to list

In [34]:
arr1=np.array(list1)
arr1
arr1=arr1+1 # we can see how elemenatry operations are possible with arrays
arr1

array([ 2,  3,  4,  5,  6,  7,  2, 11])

In [36]:
# lets find out of the data type of the element in list 
type(list1[1])

int

In [41]:
#lets find out the data type of the elements in array . we can use dtype attribute to find out the data type
arr1.dtype

dtype('int32')

In [54]:
arr2=np.array(list1, dtype='float') # we can even decide the data type of the elements while making the array 
arr2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  1., 10.])

In [55]:
arr2.dtype

dtype('float64')

In [56]:
# we can even change the "dtype" using ".astype()" method in array

arr2.astype('int')

array([ 1,  2,  3,  4,  5,  6,  1, 10])

# MORE ATTRIBUTES , INDEXING AND CONDITIONALS

In [59]:
#we already know that a 2-d array  or n-d array consists of n dimensions that can be found out . Lets explore deep
list1=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
list1 # lets make an array out of this list 

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [62]:
arr3=np.array(list1)
arr3 # a matrix formed (2-dimensional ie rows x columns ). Lets find out the no. of each dimension (ie no. of rows and columns)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
arr3.shape #this is shape attribute gives the frequency of each dimension usually a tuple


(3, 4)

In [70]:
list2=[[[21,22,23,24],[25,26,27,28]],[[29,30,31,32],[33,34,35,36]]]
arr4=np.array(list2) # we formed a 3 dimensional array (3 dimensions ie axis x rows x columns)
arr4  # Now lets try to find out the shape of this 3-d array 

array([[[21, 22, 23, 24],
        [25, 26, 27, 28]],

       [[29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [72]:
arr4.shape # again this gave a tupe of three elements (axis(2)xrows(2)xcolumns(4))

(2, 2, 4)

In [76]:
# Now lets try to grab or access specific elements of the array using indexing 
#lets start with 2-d array arr3.Keep this in mind that indexing starts with [0] always.
arr3[1,3]

8

In [80]:
#Lets try slicing as well .
#As we know [rows:rows,columns:columns] and the right hand side index is not considered 
#for example if we wrote arr3[0:2,0:3], 
#it will access elements from 0TH row to 1 row only and columns from 0th to 2 column only.
arr3[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [84]:
# Finding transpose of a 2-d matrix  using '.transpose()' function .
arr3.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [90]:
arr3[::-1]
# what it did was it reversed the rows ie it bring the first row to the last row 
# and the first low to the last .

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [93]:
# similarly we can perform the function with the columns and rows and columns as well.
arr3[::-1,::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [98]:
# We can even access elements on the basis of conditional statements like in SQL.
bool1=arr3>5
bool1 # here we gave a condition that elements must be greater than 5 must be gives a boolean dtype array .


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [102]:
# Instead of doing this we can directly write this to find an array 
arr3=arr3[arr3>5]
arr3  # this is the statement that can be used  in conditional operations

array([ 6,  7,  8,  9, 10, 11, 12])

# End of this Part .................. Thanks