# MORE ON NUMPY


In [16]:
# WE WILL TALK ABOUT CHANGING THE SHAPE OF ARRAY/MATRICES.
import numpy as np
list1=[[1,2,3,4],[5,6,7,8]]
list1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr1=np.array(list1)
arr1# the current shape is (2,4) ie total of 8 elements

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr1.size

8

In [19]:
#now lets change the shape using '.reshape()' method .
arr1.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
# we can even convert an n-dimensional array into single dimension array ie  using 2 different function .
arr1.ravel() 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
# but there is a difference between '.ravel()' and '.flatten()'
# the ravel is said to be more optimized and  creates a reference  
# while flatten creates a copy therefore in case of change in original array no change is seen .
# in ravel changes in the array would lead to change in the original since it is a reference
#data saving function because it creates a reference to the original array instead of making a copy of it unlike flatten().
# there for if changes are made , this would lead to changes in the original array as well.
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arrcopy=arr1.flatten()
arrcopy # here we created a copy using flatten , we see change in the arrcopy wont change anything in the original array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
# but performing the same operation with ".ravel()" function will create altogether change in the original as well.
# ravel() creates a reference  instead .
arrcopy1=arr1.ravel()
arrcopy1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
# now we will change the data type of "arrcopy1" and same will be reflected in original arr1 as wel

arr1[0,0]=-8
arr1


array([[-8,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [26]:
# we see the change as the reference worked for ravel
arrcopy1

array([-8,  2,  3,  4,  5,  6,  7,  8])

# Logspace ,Linespace,Range,Array Repitition

In [28]:
arr1 # now lets try to form a new array on line scale and log scale

array([[-8,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [39]:
# range type array formation 
arr4=np.arange(1,52,2,dtype="int")# here the attributes are start ,stop , step , dtype 
arr4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51])

In [40]:
# lets find out the size and shape of this array formed 
arr4.size

26

In [41]:
arr4.shape


(26,)

In [43]:
#lets change the shape of this now 
arr4.reshape(2,13)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51]])

In [53]:
#lets try array on log and linescale now 
# lets start with array on linescale(linespace) first 
arr5=np.linspace(1,50,40)# the attributes are start ,stop , and no. of elements that we want 
arr5

array([ 1.        ,  2.25641026,  3.51282051,  4.76923077,  6.02564103,
        7.28205128,  8.53846154,  9.79487179, 11.05128205, 12.30769231,
       13.56410256, 14.82051282, 16.07692308, 17.33333333, 18.58974359,
       19.84615385, 21.1025641 , 22.35897436, 23.61538462, 24.87179487,
       26.12820513, 27.38461538, 28.64102564, 29.8974359 , 31.15384615,
       32.41025641, 33.66666667, 34.92307692, 36.17948718, 37.43589744,
       38.69230769, 39.94871795, 41.20512821, 42.46153846, 43.71794872,
       44.97435897, 46.23076923, 47.48717949, 48.74358974, 50.        ])

In [57]:
# lets find out how to produce array on logspace
arr6=np.logspace(0,50,30)
arr6
#This is log scale  for no. between log scale 0 to 50 , for 30 elements

array([1.00000000e+00, 5.29831691e+01, 2.80721620e+03, 1.48735211e+05,
       7.88046282e+06, 4.17531894e+08, 2.21221629e+10, 1.17210230e+12,
       6.21016942e+13, 3.29034456e+15, 1.74332882e+17, 9.23670857e+18,
       4.89390092e+20, 2.59294380e+22, 1.37382380e+24, 7.27895384e+25,
       3.85662042e+27, 2.04335972e+29, 1.08263673e+31, 5.73615251e+32,
       3.03919538e+34, 1.61026203e+36, 8.53167852e+37, 4.52035366e+39,
       2.39502662e+41, 1.26896100e+43, 6.72335754e+44, 3.56224789e+46,
       1.88739182e+48, 1.00000000e+50])

In [58]:
# How to make the whole array copy 
arr1

array([[-8,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [61]:
# tile repeats the whole array instead of elementary operation 
np.tile(arr1,3) # the attributes for the array you want to repeat and the no. of times you want to repeat 


array([[-8,  2,  3,  4, -8,  2,  3,  4, -8,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8]])

In [64]:
np.repeat(arr1,4) # see the difference between repeat and tile function 

array([-8, -8, -8, -8,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,
        5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8])

# Random module in numpy and Unique values in array 


In [71]:
# Lets introduce the random module in this numpy series 
import random
arr_1=np.random.rand(6,3,3)
# remember the attirbutes refer to the size of the array (ie no. od rows and columns or simply dimension ).
# we can even make three dimension (ie axis x rows x columns ) or more .
arr_1


array([[[0.38300673, 0.11383703, 0.38843032],
        [0.88286057, 0.50076128, 0.45045586],
        [0.88649982, 0.76862798, 0.23961626]],

       [[0.52888187, 0.3646662 , 0.95177824],
        [0.22330864, 0.84493426, 0.76810685],
        [0.18510164, 0.32156328, 0.53040455]],

       [[0.53030933, 0.02086935, 0.99239966],
        [0.65948785, 0.73082578, 0.9128747 ],
        [0.74771799, 0.70111294, 0.11086224]],

       [[0.07583962, 0.48308124, 0.88718107],
        [0.91141765, 0.71190102, 0.44697462],
        [0.38471525, 0.69691117, 0.92074328]],

       [[0.13216838, 0.76013241, 0.84326283],
        [0.84694852, 0.60101464, 0.66829517],
        [0.54797298, 0.70273413, 0.30592635]],

       [[0.81094179, 0.93798609, 0.38435129],
        [0.07144961, 0.15329089, 0.87143057],
        [0.26490126, 0.02014832, 0.25029535]]])

In [75]:
# lets use random integer funtion 
arr_2=np.random.randint(20,size=[2,3])#the attributes is different ie.the last no. and the size
arr_2

array([[ 2,  2,  7],
       [18,  8, 10]])

In [86]:
# If you want to make an array with the with same random number 
np.random.seed(0) # this seed function make sure we get the same random module for a particular attribute (here it is "0")
arr_3=np.random.randint(2,size=(2,3))
arr_3

array([[0, 1, 1],
       [0, 1, 1]])

In [93]:
# if you would change the seed attribute to "1 or 2" then the set of random numbers in arr_3 will change.(shift +tabx2 to read the 
#documention of the functions )

In [102]:
# now suppose you have an array and you want to find out the unique elements in the array and their frequency 
# for this we use "np.unique" function
list2=[[1,2,2,3],[4,4,5,5]]
arr_6=np.array(list2)
arr_6
number,counts=np.unique(arr_6,return_counts=True)# here we asked for the unique no. in the array and the no. of their counts
number


array([1, 2, 3, 4, 5])

In [105]:
counts # the above numbers occured these many times ie the counts of these numbers

array([1, 2, 1, 2, 2])

# ENd  of this Part ........